export const screens = {
  AddPost: 'AddPost',
  AddPostModal: 'AddPostModal',
  Main: 'Main',
  Login: 'Login',
  Register: 'Register',
  GuestMode: 'GuestMode',
  Browse: 'Browse',
  Filter: 'Filter',
  Inbox: 'Inbox',
  Profile: 'Profile',
  Saved: 'Saved',
  Product: 'Product',
  Settings: 'Settings',
  WebView: 'WebView',
  Chat: 'Chat',
  Init: 'Init',
};
